# Generated by Django 5.0.1 on 2024-05-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0010_remove_appointment_message'),
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.doctor'),
        ),
    ]
