# Generated by Django 5.0.1 on 2024-05-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0012_appointment_billed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='billed',
        ),
    ]
