# Generated by Django 5.0.1 on 2024-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0013_remove_appointment_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
