# Generated by Django 5.0.1 on 2024-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0015_rename_fullname_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(default=9404733748, max_length=10),
        ),
    ]
