# Generated by Django 5.0.1 on 2024-06-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0018_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
