# Generated by Django 5.0.6 on 2024-05-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='department')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('from_day', models.CharField(max_length=20)),
                ('to_day', models.CharField(max_length=20)),
                ('timing_from', models.CharField(max_length=20)),
                ('timing_to', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='doctor')),
                ('department', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.department')),
            ],
        ),
    ]
