# Generated by Django 5.0.1 on 2024-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(default=False, max_length=255)),
                ('doctor', models.CharField(default=False, max_length=255)),
                ('appointment_charge_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('appointment_quantity', models.PositiveIntegerField(default=1)),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('service_quantity', models.PositiveIntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
