# Generated by Django 5.0.1 on 2024-05-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0014_appointment_billed'),
        ('hospital_staff', '0003_invoice_appointment_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.appointment'),
        ),
    ]
