# Generated by Django 5.0.1 on 2024-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_staff', '0005_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointment_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
